	cmake_minimum_required(VERSION 2.6)
	add_executable(	BinaryTree BinaryTree.cpp	)
	add_executable(	BinaryTreeNode BinaryTreeNode.cpp	)
	add_executable(	RBNode RBNode.cpp	)
	add_executable(	test test.cpp	)
	add_executable(	TestStructures TestStructures.cpp	)
	add_executable(	BinaryTree BinaryTree.h	)
	add_executable(	BinaryTreeNode BinaryTreeNode.h	)
	add_executable(	RBNode RBNode.h	)
	add_executable(	TestStructures TestStructures.h	)

